server:
  port: 8085
  servlet:
    context-path: /

info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@

management:
  endpoints:
    web:
      base-path: / 
      exposure:
        include: health, info, metrics, prometheus
  info:
    env:
      enabled: true